# Generated by Django 4.1.1 on 2022-09-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_category_shop_remove_item_label_remove_item_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="shop",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="ecommerce.shop"),
        ),
    ]
