# Generated by Django 4.1.1 on 2022-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_item_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="business_hour",
            field=models.CharField(default="9am - 5pm", max_length=100),
        ),
    ]
