# Generated by Django 4.1.1 on 2022-09-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_shop_business_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(),
        ),
    ]
